---
title: "Currarini_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
library(stats) 
library(dplyr)
library(magrittr)
library(ggplot2)
library(plm)
library(lmtest)
library(broom)
library(stargazer)
library(plm)
library(broom)
library(fastDummies)
```


```{r Network stat plots without controls - comparison of raw averages}
network_stats_df <- read.csv('./data/network_stats_yearly.csv')

group_share_plot <- ggplot(data = network_stats_df, mapping = aes(x = year)) + 
  geom_ribbon(data=network_stats_df, 
              aes(ymin=group_share_f,ymax=group_share_m), fill="bisque1", alpha=0.5) +
  geom_line(aes(y = group_share_m, col = 'Male'), size = 1.05) +
  geom_line(aes(y = group_share_f, col = 'Female'), size = 1.05) + 
  ylim(c(0, 1)) + 
  xlim(c(1965, 2025)) +
  labs(x = 'Year', y = 'Population shares',
       title = 'Population gender composition') +
  scale_x_continuous(breaks = seq(1970, 2020, by = 5),
                     expand = c(0, 0)) +
  scale_color_manual(values = c("Male" = "darkblue", "Female" = "darkred", 'Difference' = 'black')) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom',
        legend.direction = "horizontal",
        legend.title=element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank())

group_share_plot
ggsave('./plots/population_shares.png',
       group_share_plot,
       width = 6, height = 4)

num_ties_plot <- ggplot(data = network_stats_df, mapping = aes(x = year)) + 
  geom_ribbon(data=network_stats_df, 
              aes(ymin=avg_num_ties_f,ymax=avg_num_ties_m), fill="bisque1", alpha=0.5) +
  geom_line(aes(y = avg_num_ties_m, col = 'Male'), size = 1.05) +
  geom_line(aes(y = avg_num_ties_f, col = 'Female'), size = 1.05) + 
  ylim(c(0.3, 2.6)) + 
  labs(x = 'Year', y = 'Average number of ties',
       title = 'Collaborative ties') +
  scale_x_continuous(breaks = seq(1970, 2020, by = 5),
                     expand = c(0, 0)) +
  scale_color_manual(values = c("Male" = "darkblue", "Female" = "darkred", 'Difference' = 'black')) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = 'bottom',
        legend.direction = "horizontal",
        legend.title=element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_text(angle = 90, vjust = 1, hjust=0.5))

num_ties_plot

ggsave('./plots/Currarini_tie_diff.png',
       num_ties_plot,
       width = 6, height = 4)

```


```{r Gap significance}
# read in per-author data
per_author_stats <- read.csv('./data/per_author_net_stats_5yroll_full.csv',
                              row.names = 1)
per_author_stats['pub_year_factor'] = factor(per_author_stats$pub_year)


# gender differences in number of ties

number_of_ties_plm <- plm(degree ~ female + female * pub_year + experience_year + 
                             A + B + C + D + E + F + G + H + I + J + K + L + M + N + O + P + Q + R + Y + Z,
                           data = per_author_stats,
                           index = 'pub_year', #index = c('author_id', 'pub_year'), # both FE
                           model = 'within') 

# calculate confidence intervals for all female-year interactions
all_coefs <- tidy(number_of_ties_plm)
conf_ints = confint(number_of_ties_plm, level = 0.95)
all_coefs = cbind(all_coefs, conf_ints)
female_year_coefs <- all_coefs[grep('female', all_coefs$term), ]
years = seq(1970, 2020)
female_year_coefs = cbind(female_year_coefs, years)

# Plot
p_ties <- ggplot(female_year_coefs, aes(years, estimate)) +
  geom_errorbar(data =female_year_coefs, aes(ymin = `2.5 %`, ymax = `97.5 %`),
                color = 'chartreuse3') +
  geom_point() +
  geom_hline(yintercept = 0, linetype = 2) +
  #ggtitle('Number of collaborative ties - gender difference') +
  ylim(c(-1.9, 1.1)) +
  scale_x_continuous(breaks = seq(1970, 2020, by=5),
                     expand = c(0.03, 0.03)) +
  labs(title = 'Gender difference in average number of ties over time',
       x = 'Year',
       y = 'Difference in the gender gap in number of ties') +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.y = element_text(angle = 90, vjust = 1, hjust=0.5))

ggsave('./plots/Currarini_gender_diff_confints.png',
       p_ties,
       width = 6, height = 4)

p_ties

# Create LaTeX table with coefficients, edit in LaTeX

stargazer::stargazer(
  list(number_of_ties_plm), type = "text",
  dep.var.caption = "Pooled OLS",
  dep.var.labels = 'Number of ties',
  keep=c("female"),
  omit.stat = c("rsq"),
  notes.align = "l",
  single.row = TRUE,
  out = './result_tables/Currarini_gender_diff_in_num_ties.tex')

```

